<?php

/**
 * drupilot — rector.php
 * drupilot-template-version: 5
 *
 * Self-contained Rector configuration for porting a Drupal module/theme to a
 * newer Drupal major. Modeled on vendor/palantirnet/drupal-rector/rector.php.
 *
 * Generated by scripts/env/render-templates.sh (or run-rector.sh when
 * rector.php is missing) from the upgrade plan (scripts/analysis/upgrade-path.sh,
 * ADR 0017/0019), which fills in the extension path, the Drupal sets of the
 * plan's hops, the backwards-compatibility settings, the PHP floor
 * 8.3 and the rules skipped. Its sha256 is kept in the lock: an
 * untouched copy is regenerated when the plan moves; a hand-edited one is never
 * replaced without --force.
 *
 * Drupal sets: the per-minor sets of each hop's family (Drupal10SetList::
 * DRUPAL_100 ... for a port to Drupal 11), up to the test-bed's minor, never
 * the target's own sets (they would rewrite to APIs the kept previous major
 * lacks). drupal-rector's own aggregates (DRUPAL_10) also register its
 * bootstrap file, so it is registered here too. A set the installed
 * drupal-rector does not declare is left out (defined()).
 *
 * The PHP floor (ADR 0002): the code must keep running on the lowest PHP the
 * declared core range and the composer require.php admit (never above
 * DRUPILOT_PHP_TARGET), e.g. 8.1 for ^10 || ^11. Rector drops every
 * version-bound rule above ->withPhpVersion(), and the level sets stop at the
 * floor too, so nothing is modernized past what that PHP can run. A floor of
 * 8.5 uses the php84 sets (no php85 set is assumed). PHP deprecation fixes
 * whose output still runs on the floor (an implicitly nullable parameter
 * becoming ?Foo, deprecated in PHP 8.4) run in a second, narrow pass with
 * rector-compat.php, right after this one, when the floor is below 8.4.
 *
 * The complementary dbuytaert/drupal-digests AI rule layer is NOT wired in
 * here. It runs as a separate, optional pass referenced by its own config:
 *   vendor/bin/rector process web/modules/custom/d11_php_only \
 *     --config "$DIGESTS_CACHE/rector/all.php" --dry-run
 * (Run the official palantirnet/drupal-rector pass first, then digests.)
 *
 * Risky PHP-modernization rules are SKIPPED (see $drupilotRiskySkips below).
 * None of them is a Drupal 11 compatibility requirement, and each one breaks
 * Drupal code:
 *   ArrayToFirstClassCallableRector  — turns Form/Render API callbacks such as
 *       '#submit' => [[$this, 'submitX']] into $this->submitX(...). A closure
 *       is not serializable, so a cached form (#ajax, form state cache) fatals.
 *   AddOverrideAttributeToOverriddenMethodsRector — adds #[\Override] by looking
 *       at the sandbox core only. A method that exists in the parent only on
 *       newer cores (e.g. ContentEntityStorageBase::buildRevisionCacheId(),
 *       11.3+) then fatals on PHP 8.3+ with every older core you still declare.
 *   ReadOnlyPropertyRector / ReadOnlyClassRector — readonly properties cannot
 *       be re-initialized by DependencySerializationTrait::__wakeup() (forms,
 *       plugins, controllers that get serialized).
 *   NullToStrictStringFuncCallArgRector — adds (string) casts that change
 *       semantics and fail stricter project PHPStan levels.
 *   SleepToSerializeRector / WakeupToUnserializeRector — rewrite __sleep() /
 *       __wakeup(), which DependencySerializationTrait defines for forms,
 *       plugins and services, into __serialize() / __unserialize().
 *   AddOverrideAttributeToOverriddenPropertiesRector — #[\Override] on a
 *       property needs PHP 8.5 and the parent property on every core declared.
 * FunctionFirstClassCallableRector is NOT skipped: it only rewrites a string
 * argument passed to a PHP built-in whose parameter is typed `callable`
 * (array_map('trim', ...) -> array_map(trim(...), ...)), so it can never reach
 * a Form/Render API array key; the closure is consumed immediately.
 * The list is filtered with class_exists() because Rector 2.x refuses to start
 * when withSkip() names a rule class that does not exist in the installed
 * version. scripts/analysis/check-port-safety.sh re-checks the result (the
 * digests pass runs with its own config and does not inherit these skips).
 *
 * Rector needs the Drupal core tree present (no database). Run with --dry-run
 * first, review the diff, then apply.
 */

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\ValueObject\PhpVersion;

// The Drupal sets of the plan's hops, by constant name: defined() leaves out a
// set the installed drupal-rector does not declare, so this config always loads.
$drupilotSets = array_map('constant', array_values(array_filter([

], 'defined')));

// drupal-rector's bootstrap file (Drupal's test namespaces and phpstan-drupal's
// service map, for type inference), which its aggregate sets register.
$drupilotBootstrap = $drupilotSets === [] ? [] : array_values(array_filter([
  __DIR__ . '/vendor/palantirnet/drupal-rector/config/drupal-phpunit-bootstrap-file.php',
], 'file_exists'));

// Rules skipped on purpose (see the header). String FQCNs + class_exists keep
// this config loadable on any Rector 2.x.
$drupilotRiskySkips = array_values(array_filter([
  'Rector\\Php81\\Rector\\Array_\\ArrayToFirstClassCallableRector',
  'Rector\\Php83\\Rector\\ClassMethod\\AddOverrideAttributeToOverriddenMethodsRector',
  'Rector\\Php81\\Rector\\Property\\ReadOnlyPropertyRector',
  'Rector\\Php82\\Rector\\Class_\\ReadOnlyClassRector',
  'Rector\\Php81\\Rector\\FuncCall\\NullToStrictStringFuncCallArgRector',
  'Rector\\Php85\\Rector\\Class_\\SleepToSerializeRector',
  'Rector\\Php85\\Rector\\Class_\\WakeupToUnserializeRector',
  'Rector\\Php85\\Rector\\Property\\AddOverrideAttributeToOverriddenPropertiesRector',
], 'class_exists'));

$drupilotConfig = RectorConfig::configure()
  // Process only the target extension. Other paths (e.g. core, contrib) are
  // left untouched.
  ->withPaths([
    'web/modules/custom/d11_php_only',
  ])
  // Never rewrite third-party code or build/test artifacts, and never apply
  // the risky modernization rules listed above.
  ->withSkip(array_merge([
    '*/vendor/*',
    '*/node_modules/*',
  ], $drupilotRiskySkips))
  // The Drupal deprecation sets of the plan's hops.
  ->withSets($drupilotSets)
  ->withBootstrapFiles($drupilotBootstrap)
  // The PHP floor 8.3 (the plan's php.floor). Rector drops every
  // version-bound rule above it, and the level sets stop at it. Compat fixes
  // for newer PHP run in rector-compat.php.
  ->withPhpVersion(PhpVersion::PHP_83)
  ->withPhpSets(php83: true)
  // Drupal extensions Rector should treat as PHP so hooks and *.module files
  // are processed too.
  ->withFileExtensions([
    'php',
    'module',
    'theme',
    'install',
    'inc',
    'profile',
    'engine',
  ]);

// Backwards-compatible rewrites (DeprecationHelper) for every core the declared
// range keeps, from 11.0 on (the plan's rector.bc).
$drupilotConfig = static function (RectorConfig $rectorConfig) use ($drupilotConfig): void {
  $drupilotConfig($rectorConfig);
  if (class_exists(\DrupalRector\Services\DrupalRectorSettings::class)) {
    $rectorConfig->singleton(\DrupalRector\Services\DrupalRectorSettings::class, static fn () => (new \DrupalRector\Services\DrupalRectorSettings())
      ->enableBackwardCompatibility()
      ->setMinimumCoreVersionSupported('11.0.0'));
  }
};
return $drupilotConfig;
