#!/usr/bin/env bash
# =============================================================================
# drupilot — scripts/dev/gen-docs.sh
# Generate the reference pages of the docs site from their sources of truth
# (a developer/CI tool: no command, skill or hook calls it; the `docs` gate of
# scripts/dev/check.sh runs --check). Each page starts with a GENERATED
# comment and is never edited by hand:
#   reference/scripts.md            every scripts/{analysis,contrib,env,tests,dev}/*.sh
#                                   header (print_usage; no script is run)
#   reference/commands.md           commands/*.md frontmatter
#   reference/skills-and-agents.md  skills/*/SKILL.md and agents/*.md frontmatter
#   reference/configuration.md      config/config-reference.json + config/defaults.json
#   reference/choices.md            config/choices.json
#   reference/toolchain.md          config/toolchain-reference.json
#   reference/deprecations.md       config/deprecations.json (Drupal's deprecations)
# The output is byte-identical on every platform (bash 3.2, BSD/BusyBox,
# mawk, jq 1.6): sorted with LC_ALL=C, no timestamps, paths or tool versions.
# A "See" link is written only when its docs page exists.
#
# Usage:
#   scripts/dev/gen-docs.sh [--out DIR] [--check] [--json] [-h|--help]
#     --out DIR  where to write the pages (default: docs/reference)
#     --check    generate into a temp dir outside the repo and compare it with
#                the committed pages (the diff goes to STDERR); writes nothing
#     --json     {ok, generated:[...], drift:[...]} on STDOUT
#
# Requires bash >= 3.2 and jq. Exit codes: 0 generated / no drift · 1 drift
# (--check) or a usage error.
# =============================================================================
set -euo pipefail

# shellcheck source=../lib/common.sh
. "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$REPO/docs/reference"; CHECK=0; AS_JSON=0
export LC_ALL=C

usage() { print_usage "${BASH_SOURCE[0]}"; }
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out) OUT="${2:-}"; shift 2 || die "--out needs a directory" 1;;
    --out=*) OUT="${1#*=}"; shift;;
    --check) CHECK=1; shift;;
    --json) AS_JSON=1; shift;;
    -h|--help) usage; exit 0;;
    *) die "Unknown argument: $1 (see --help)" 1;;
  esac
done
have_cmd jq || die "jq is required by scripts/dev/gen-docs.sh" 1
PAGES="scripts commands skills-and-agents configuration choices toolchain deprecations"
GEN='<!-- GENERATED by scripts/dev/gen-docs.sh — do not edit; edit the source and re-run -->'

# jq helper: escape < and > outside `code spans` (Markdown would read them as
# HTML), so prose like "<root>/.drupilot" survives.
JQ_ESC='def esc: tostring | split("`") | to_entries | map(if .key % 2 == 0 then .value | gsub("<"; "&lt;") | gsub(">"; "&gt;") else .value end) | join("`");'

# fm_json <file> -> the YAML frontmatter as a JSON object of strings (plain,
# "double", 'single' and folded >- / > / | block scalars).
fm_json() {
  awk 'BEGIN { RSEP = sprintf("%c", 30); FSEP = sprintf("%c", 31) }
       function flush() { if (k != "") { printf "%s%s%s%s", k, FSEP, v, RSEP }; k = ""; v = ""; blk = "" }
       NR == 1 && /^---/ { f = 1; next }
       f && /^---/ { flush(); exit }
       !f { next }
       blk != "" && /^[[:space:]]/ {
         line = $0; sub(/^[[:space:]]+/, "", line)
         if (blk == "|") v = (v == "" ? line : v "\n" line)
         else if (line == "") v = v "\n"
         else v = (v == "" || v ~ /\n$/ ? v line : v " " line)
         next }
       /^[A-Za-z0-9_-]+:/ {
         flush()
         k = $0; sub(/:.*/, "", k)
         val = $0; sub(/^[A-Za-z0-9_-]+:[[:space:]]*/, "", val)
         if (val ~ /^[>|][-+]?[[:space:]]*$/) { blk = substr(val, 1, 1); v = ""; next }
         if (val ~ /^".*"$/) { val = substr(val, 2, length(val) - 2); gsub(/\\"/, "\"", val); gsub(/\\\\/, "\\", val) }
         else if (val ~ /^'"'"'.*'"'"'$/) { val = substr(val, 2, length(val) - 2); gsub(/'"''"'/, "'"'"'", val) }
         v = val; next }
       END { flush() }' "$1" \
    | jq -Rs 'split("\u001e") | map(select(length > 0) | split("\u001f") | {(.[0]): (.[1:] | join("\u001f"))}) | add // {}'
}

# page_exists <docs-relative path> -> 0 when the page is in docs/.
page_exists() { [[ -f "$REPO/docs/$1" ]]; }

gen_scripts() {
  local g f
  printf '%s\n\n# Scripts\n\n' "$GEN"
  printf 'Every script of `scripts/`, by group, with the usage its header documents (`-h` / `--help` prints the same text). A script never prints anything else on STDOUT than its payload; logs go to STDERR.\n'
  for g in analysis contrib env tests dev; do
    printf '\n## %s\n' "$g"
    for f in $(cd "$REPO/scripts/$g" && ls ./*.sh 2>/dev/null | sed 's#^\./##' | sort); do
      printf '\n### %s/%s\n\n```text\n' "$g" "$f"
      print_usage "$REPO/scripts/$g/$f" | sed -e 's/[[:space:]]*$//'
      printf '```\n'
    done
  done
}

gen_commands() {
  local f
  printf '%s\n\n# Commands\n\n' "$GEN"
  printf 'The slash commands of drupilot, from their frontmatter (`commands/*.md`). In a session that loads drupilot as a plugin, each is also reachable as `/drupilot:<name>`.\n'
  for f in $(cd "$REPO/commands" && ls ./*.md | sed 's#^\./##' | sort); do
    fm_json "$REPO/commands/$f" | jq -r --arg n "${f%.md}" "$JQ_ESC"'
      "\n## /\($n)\n\n\(.description // "" | esc)\n",
      (if (.["argument-hint"] // "") != "" then "- **Arguments:** `\(.["argument-hint"])`" else empty end),
      (if (.["allowed-tools"] // "") != "" then "- **Allowed tools:** \(.["allowed-tools"])" else empty end),
      (if (.["disable-model-invocation"] // "") == "true" then "- **User-invocable only:** Claude never runs it on its own (`disable-model-invocation: true`)." else empty end)'
  done
}

gen_skills_agents() {
  local d f
  printf '%s\n\n# Skills and agents\n\n' "$GEN"
  printf 'The skills (`skills/*/SKILL.md`) and subagents (`agents/*.md`) the commands load, from their frontmatter.\n\n## Skills\n'
  for d in $(cd "$REPO/skills" && ls -d ./*/ | sed 's#^\./##; s#/$##' | sort); do
    fm_json "$REPO/skills/$d/SKILL.md" | jq -r --arg n "$d" "$JQ_ESC"'"\n### \(.name // $n)\n\n\(.description // "" | esc)"'
  done
  printf '\n## Agents\n'
  for f in $(cd "$REPO/agents" && ls ./*.md | sed 's#^\./##' | sort); do
    fm_json "$REPO/agents/$f" | jq -r --arg n "${f%.md}" "$JQ_ESC"'
      "\n### \(.name // $n)\n\n\(.description // "" | esc)",
      (if (.tools // "") != "" then "\n- **Tools:** \(.tools)" else empty end)'
  done
}

gen_configuration() {
  local see_ok="" p
  # The "see" pages that exist, so a link never points at a missing page.
  for p in $(jq -r '[(.keys, .runtime_only, .patterns)[] | .see // empty] | unique[]' "$REPO/config/config-reference.json"); do
    page_exists "$p" && see_ok="$see_ok$p "
  done
  printf '%s\n\n# Configuration\n\n' "$GEN"
  jq -r --slurpfile d "$REPO/config/defaults.json" --arg seeok "$see_ok" "$JQ_ESC"'
    def dflt($e): if $e.default_ref == null then "none"
      elif ($e.default_ref | startswith("defaults.json#/")) then
        ($d[0] | getpath($e.default_ref | ltrimstr("defaults.json#/") | split("/"))) as $v
        | if $v == "" then "empty" else "`\($v | tojson | ltrimstr("\"") | rtrimstr("\""))`" end
      elif ($e.default_ref | startswith("choices.json#/")) then "per choice (see Choices)"
      else "`\($e.default_ref)`" end;
    def see($e): if ($e.see // "") != "" and ($seeok | split(" ") | index($e.see)) != null
      then "- **See:** [\($e.see)](../\($e.see))" else empty end;
    def entry($name; $e):
      "\n### `\($name)`\n\n\($e.description | esc)\n",
      "- **Default:** \(dflt($e))",
      "- **Type:** \($e.type)" + (if $e.enum != null then " — one of " + ([$e.enum[] | if . == "" then "empty" else "`\(.)`" end] | join(", ")) else "" end),
      see($e);
    "Every `DRUPILOT_*` setting drupilot reads, from `config/config-reference.json` (descriptions) and `config/defaults.json` (defaults).",
    "",
    "A setting resolves as **environment variable > the project'"'"'s `.drupilot.json` (at the Drupal root, where tabbed choices are remembered) > `config/defaults.json` > the caller'"'"'s default**: the environment always wins. A renamed setting keeps working for all of 1.x through an alias (`config/migrations.json`), with a one-time deprecation warning.",
    "",
    "## Settings",
    (.keys | to_entries | sort_by(.key)[] | select(.value.tier == "public" or .value.tier == "advanced") | entry(.key; .value)),
    "",
    "## Environment-only and remembered settings",
    "",
    "These have no default in `config/defaults.json`.",
    (.runtime_only | to_entries | sort_by(.key)[] | select(.value.tier == "public" or .value.tier == "advanced") | entry(.key; .value)),
    "",
    "## Setting families",
    (.patterns | to_entries | sort_by(.key)[] | select(.value.tier == "public" or .value.tier == "advanced") | entry(.key; .value)),
    "",
    "## Internal",
    "",
    "Not user configuration (free to change within 1.x): " + ([(.keys, .runtime_only, .patterns) | to_entries[] | select(.value.tier == "internal") | "`\(.key)`"] | sort | join(", ")) + "."
  ' "$REPO/config/config-reference.json"
}

gen_choices() {
  printf '%s\n\n# Choices\n\n' "$GEN"
  jq -r "$JQ_ESC"'
    "The forks drupilot asks about as tabs, from `config/choices.json`. The recommended option is pre-selected; the answer is remembered in the project'"'"'s `.drupilot.json` when the choice has a setting. `DRUPILOT_CHOICE_<KEY>` pre-answers a tab (an invalid value is ignored with a warning), except where it says it is never pre-answered.",
    (.choices | to_entries | sort_by(.key)[] | .key as $k | .value as $c |
      "\n## \($k)\n",
      "- **Tab:** \($c.header // "" | esc)",
      "- **Command:** `\($c.command // "")`",
      (if $c.options then "- **Options:** " + ([$c.options[] | "`\(tostring)`"] | join(", ")) + (if $c.multi then " (several may be chosen)" else "" end) else empty end),
      (if $c.default != null then "- **Default:** `\($c.default | tostring)`" else empty end),
      (if $c.preanswer == false then "- **Pre-answer:** never (`DRUPILOT_CHOICE_\($k)` is ignored)" else "- **Pre-answer:** `DRUPILOT_CHOICE_\($k)`" end),
      (if $c.persist_key then "- **Remembered as:** `\($c.persist_key)`" else empty end),
      (if $c.note then "\n\($c.note | esc)" else empty end))
  ' "$REPO/config/choices.json"
}

gen_toolchain() {
  printf '%s\n\n# Toolchain\n\n' "$GEN"
  jq -r "$JQ_ESC"'
    "The known-good development toolchain `scripts/env/install-toolchain.sh` installs when the project lock does not pin the whole set, from `config/toolchain-reference.json`. A version enters it only after it was installed and verified together in a DDEV test-bed.",
    "",
    "Verified on \(.verified_on) with Drupal core \(.verified_with.drupal_core // "?"), PHP \(.verified_with.php // "?"), DDEV \(.verified_with.ddev // "?") and \(.verified_with.subject // "a test subject" | esc).",
    "",
    "## Packages",
    "",
    "| Package | Version |",
    "|---|---|",
    (.toolchain | to_entries[] | "| `\(.key)` | `\(.value)` |"),
    "",
    "## Remediation packages",
    "",
    "Reinstalled together when the toolchain smoke test fails: " + ([.remediation_packages[] | "`\(.)`"] | join(", ")) + ".",
    "",
    "## Known broken combinations",
    (.known_broken[] |
      "\n- " + ([.packages | to_entries[] | "`\(.key)` \(.value | esc)"] | join(" with ")) + ": \(.symptom | esc)",
      "  \(.cause | esc)")
  ' "$REPO/config/toolchain-reference.json"
}

gen_deprecations() {
  printf '%s\n\n# Drupal deprecations\n\n' "$GEN"
  jq -r "$JQ_ESC"'
    .change_records_search as $cr |
    "The Drupal API deprecations `scripts/analysis/explain-deprecations.sh` explains, from `config/deprecations.json`. Each pattern is a POSIX extended regular expression matched against the analyzers'"'"' messages. (drupilot'"'"'s own deprecated settings are a different page.)",
    (.deprecations | sort_by(.symbol // .pattern)[] |
      "\n## `\(.symbol // .pattern)`\n",
      "- **Pattern:** `\(.pattern)`",
      (if .category then "- **Category:** \(.category)" else empty end),
      "- **What changed:** \(.why // "" | esc)",
      "- **Fix:** \(.fix // "" | esc)",
      "- **Change records:** <\($cr)\(.symbol // .pattern | @uri)>")
  ' "$REPO/config/deprecations.json"
}

generate() {  # <dir>
  local d="$1" p
  mkdir -p "$d"
  for p in $PAGES; do
    case "$p" in
      scripts) gen_scripts;;
      commands) gen_commands;;
      skills-and-agents) gen_skills_agents;;
      configuration) gen_configuration;;
      choices) gen_choices;;
      toolchain) gen_toolchain;;
      deprecations) gen_deprecations;;
    esac > "$d/$p.md"
  done
}

if [[ "$CHECK" == "1" ]]; then
  TMP="$(mktemp -d "${TMPDIR:-/tmp}/drupilot-gendocs.XXXXXX")"
  trap 'rm -rf "$TMP"' EXIT
  generate "$TMP/out"
  DRIFT=""
  for p in $PAGES; do
    if ! cmp -s "$TMP/out/$p.md" "$OUT/$p.md"; then
      DRIFT="$DRIFT $p"
      diff -u "$OUT/$p.md" "$TMP/out/$p.md" 2>&1 | head -n 40 | sed 's/^/    /' >&2 || true
    fi
  done
  if [[ -n "$DRIFT" ]]; then log_err "gen-docs.sh: generated pages drift:$DRIFT (run scripts/dev/gen-docs.sh and commit)"
  else log_ok "gen-docs.sh: the generated reference pages are up to date"; fi
  if [[ "$AS_JSON" == "1" ]]; then
    jq -n -c --arg p "$PAGES" --arg d "$DRIFT" '{ok: ($d == ""), generated: ($p | split(" ") | map(. + ".md")), drift: ($d | split(" ") | map(select(. != "") | . + ".md"))}'
  fi
  [[ -z "$DRIFT" ]]; exit $?
fi
generate "$OUT"
log_ok "gen-docs.sh: wrote $(printf '%s' "$PAGES" | wc -w | tr -d ' ') page(s) to ${OUT#"$REPO"/}"
if [[ "$AS_JSON" == "1" ]]; then
  jq -n -c --arg p "$PAGES" '{ok: true, generated: ($p | split(" ") | map(. + ".md")), drift: []}'
fi
