<?php

/**
 * drupilot — rector-compat.php
 * drupilot-template-version: 1
 *
 * The narrow compat pass (ADR 0002). scripts/analysis/run-rector.sh runs it
 * right after the official pass, when the PHP floor of rector.php is below
 * PHP 8.4 and the declared core range runs on 8.4 or later:
 *   vendor/bin/rector process web/modules/custom/legacy_widgets --config rector-compat.php
 * It registers only PHP deprecation fixes whose output still runs on that
 * floor, and no set (so no polyfill rule either):
 *   ExplicitNullableParamTypeRector — `Foo $x = NULL` (an implicitly nullable
 *       parameter, deprecated in PHP 8.4) becomes `?Foo $x = NULL`, valid
 *       since PHP 7.1.
 * withPhpVersion() is the highest PHP version among the listed rules: it only
 * lets Rector's PhpVersionedFilter keep them, it raises nothing else. The rule
 * list, not that filter, is what keeps the output valid on the floor.
 *
 * Generated by scripts/env/render-templates.sh (or run-rector.sh when it is
 * missing). Paths, skips and file extensions are the same as in rector.php.
 */

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\ValueObject\PhpVersion;

// The same skip list as rector.php. String FQCNs + class_exists keep this
// config loadable on any Rector 2.x.
$drupilotRiskySkips = array_values(array_filter([
  'Rector\\Php81\\Rector\\Array_\\ArrayToFirstClassCallableRector',
  'Rector\\Php83\\Rector\\ClassMethod\\AddOverrideAttributeToOverriddenMethodsRector',
  'Rector\\Php81\\Rector\\Property\\ReadOnlyPropertyRector',
  'Rector\\Php82\\Rector\\Class_\\ReadOnlyClassRector',
  'Rector\\Php81\\Rector\\FuncCall\\NullToStrictStringFuncCallArgRector',
  'Rector\\Php85\\Rector\\Class_\\SleepToSerializeRector',
  'Rector\\Php85\\Rector\\Class_\\WakeupToUnserializeRector',
  'Rector\\Php85\\Rector\\Property\\AddOverrideAttributeToOverriddenPropertiesRector',
], 'class_exists'));

// The compat rules (config/php/rules.json kind "compat"). An unknown class in
// withRules() is fatal too, so the list is filtered the same way.
$drupilotCompatRules = array_values(array_filter([
  'Rector\\Php84\\Rector\\Param\\ExplicitNullableParamTypeRector',
], 'class_exists'));

return RectorConfig::configure()
  ->withPaths([
    'web/modules/custom/legacy_widgets',
  ])
  ->withSkip(array_merge([
    '*/vendor/*',
    '*/node_modules/*',
  ], $drupilotRiskySkips))
  ->withPhpVersion(PhpVersion::PHP_84)
  ->withRules($drupilotCompatRules)
  ->withFileExtensions([
    'php',
    'module',
    'theme',
    'install',
    'inc',
    'profile',
    'engine',
  ]);
